version: '3'
services:
  proxy:
    build:
      context: ./
      dockerfile: nginx.Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - rest
      - main_page
      - participate_page
      - crew_page
      - rest_static
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    logging:
      options:
       max-size: "1g"
  participate_page:
    build:
      context: ../../
      dockerfile: devops/phoenix-development/nodejs.Dockerfile
    environment:
      BASE_URL: "http://api.dev.phoenixlan.no:3000"
      HOST: "http://delta.dev.phoenixlan.no:3000"
      REACT_APP_OAUTH_CLIENT_ID: "phoenix-delta-dev"
      REACT_APP_MAIN_SITE: "http://dev.phoenixlan.no:3000"
    env_file:
      - .npm_env
    entrypoint:
      - bash
      - "-c"
      - "cd ../phoenixjs-1.0 && yarn link && cd ../phoenix && yarn link @phoenixlan/phoenix.js && yarn && yarn start"
    volumes:
      - ../../phoenixparticipate-v1:/srv/phoenix
      - ../../phoenixjs-1.0:/srv/phoenixjs-1.0
    logging:
      options:
       max-size: "1g"
  main_page:
    build:
      context: ../../
      dockerfile: devops/phoenix-development/nodejs.Dockerfile
    ports:
      - 35729:35729
    volumes:
      - ../../phoenixmain-v1:/srv/phoenix
    logging:
      options:
       max-size: "1g"
  rest_static:
    build:
      context: ../../
      dockerfile: devops/phoenix-development/nodejs.Dockerfile
    volumes:
      - ../../phoenixapi-v1/staticContent:/srv/phoenix
    logging:
      options:
       max-size: "1g"
  rest:
    build:
      context: ../../phoenixapi-v1/
      dockerfile: docker/development/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    env_file: 
      - .env
      - .db_env
      - .mailgun_env
    environment:
      DEBUG: "yes"
    volumes:
      - ../../phoenixapi-v1/phoenixRest:/srv/phoenixRest/phoenixRest
      - ../../phoenixapi-v1/alembic:/srv/phoenixRest/alembic
      - ./files:/files
    logging:
      options:
       max-size: "1g"
  crew_page:
    build:
      context: ../../
      dockerfile: devops/phoenix-development/nodejs.Dockerfile
    entrypoint:
      - bash
      - "-c"
      - "cd ../phoenixjs-1.0 && yarn link && cd ../phoenix && yarn link @phoenixlan/phoenix.js && yarn && yarn start"
    env_file:
      - .npm_env
      - .fa_env
    volumes:
      - ../../phoenixcrew-v1:/srv/phoenix
      - ../../phoenixjs-1.0:/srv/phoenixjs-1.0
    logging:
      options:
       max-size: "1g"
  db:
    image: postgres:alpine
    env_file: .db_env
    logging:
      options:
       max-size: "1g"
  adminer:
    depends_on:
      - db
    image: adminer
    ports:
      - 3739:8080
    logging:
      options:
       max-size: "1g"
